# Generated by Django 3.2.6 on 2021-09-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('marks', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=30)),
                ('tsubject', models.CharField(max_length=30)),
                ('sal', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
