# Generated by Django 3.2.6 on 2021-09-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_stu_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='trainer2',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.content')),
                ('adhar', models.BigIntegerField()),
                ('pincode', models.IntegerField()),
            ],
            bases=('myapp.content',),
        ),
    ]
