# Generated by Django 3.2.6 on 2021-09-21 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_content_trainer2'),
    ]

    operations = [
        migrations.CreateModel(
            name='super1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='child1',
            fields=[
                ('super1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.super1')),
                ('adhar', models.BigIntegerField()),
                ('pincode', models.IntegerField()),
            ],
            bases=('myapp.super1',),
        ),
        migrations.CreateModel(
            name='child2',
            fields=[
                ('child1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.child1')),
                ('pan', models.BigIntegerField()),
                ('passport', models.IntegerField()),
            ],
            bases=('myapp.child1',),
        ),
    ]
