# Generated by Django 3.2.6 on 2021-09-21 09:41

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_child1_child2_super1'),
    ]

    operations = [
        migrations.CreateModel(
            name='father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='son',
            fields=[
                ('father_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.father')),
                ('pan', models.BigIntegerField()),
                ('passport', models.IntegerField()),
            ],
            bases=('myapp.father', myapp.models.mother),
        ),
    ]
